global virtual class CONS_CaseTempFields {
    
    public String NombreApoderado{get;set;}
    public String NombreNuevoBeneficiario{get;set;}
    public String NombrePago{get;set;} 
    public String NombreServipag{get;set;}
    public String NombreTerceroAfectado{get;set;}
    public String ApellidoMatApoderado{get;set;}
    public String ApellidoMatNuevoBeneficiario{get;set;}
    public String ApellidoMatPago{get;set;} 
    public String ApellidoMatServipag{get;set;}
    public String ApellidoPatApoderado{get;set;}
    public String ApellidoPatNuevoBeneficiario{get;set;}
    public String ApellidoPatPago{get;set;} 
    public String ApellidoPatServipag{get;set;}
    public String RutPago{get;set;} 
    public String RutServipag{get;set;}
    public String RutNuevoBeneficiario{get;set;} 
    public String RutApoderado{get;set;}
    public String RutTerceroAfectado{get;set;}
    public String RutEmpleador{get;set;}
    public String Banco{get;set;}
    public String CodEmpleador{get;set;}
    public String Comuna{get;set;}
    public Integer CotVolRegA{get;set;}
    public Integer CotVolRegB{get;set;}
    public String NombreEmpleador{get;set;}
    public boolean DetalleDevolucion{get;set;}
    public String DiaCobro{get;set;}
    public String DiaPago{get;set;}
    public String Direccion{get;set;}
    public Date FechaNacimiento{get;set;}
    public Date FechaVigenciaEndoso{get;set;}
    public Date FechaFinSuspension{get;set;}
    public Date FechaFinVigencia{get;set;}
    public Date FechaInicioSuspension{get;set;}
    public Date FechaInicioVigencia{get;set;}
    public Date FechaVencimientoTarjeta{get;set;}
    public String Genero{get;set;}
    public String ListaCoberturas{get;set;}
    public String ListaNuevoPlan{get;set;}
    public String MesInicio{get;set;}
    public String MesFin{get;set;}
    public Integer NoDeclaracionBeneficiarios{get;set;}
    public String NuevoPlan{get;set;}
    public String NuevoRegimenSII{get;set;}
    public Boolean Fumador{get;set;}
    public Boolean PolizaTutor{get;set;}
    public Integer NoPropuesta{get;set;}
    public String NuevaPrima{get;set;}
    public String Deducible{get;set;}
    public String NuevaCobertura{get;set;}
    
    public String NoSAAP{get;set;}
    public String NombreCalle{get;set;}
    public String NombreVilla{get;set;}
    public String NuevaFrecuencia{get;set;}
    public String Institucion{get;set;}
    public double NuevaPrimaProyectada{get;set;}
    public String NuevoRegTributario{get;set;}
    public String NuevoTipoFumador{get;set;}
    public String Numero{get;set;}
    public String NoDeclaracionBenef{get;set;}
    public String NoDepto{get;set;}
    public String NoFolioDPFS{get;set;}
    public String NoPiso{get;set;}
    public Integer NoPolizaDestino{get;set;}
    public Long NoCtaTarjeta{get;set;}
    public String NoMandato{get;set;}
    public String SituacionAseguradi{get;set;}
    public String TipoCuenta{get;set;}
    public String TipoTarjeta{get;set;}
    public integer montoRescatePesos{get;set;}
    public integer montoRescateUF{get;set;}
    //--botones para rescate favor no borrar---//
    public double MontoMaximo {get;set;}
    //--------------- 
    public integer MontoPesoCotizacionA {get;set;}
    public integer MontoPesoCotizacionB {get;set;}
    public integer MontoPesoCotizacionBMayor {get;set;}
    public long TotalPesos {get;set;}
    public integer MontoPesoDepositoA {get;set;}
    public integer MontoPesoDepositoB {get;set;}
    public integer MontoPesoDepositoBMayor {get;set;}
   //--------------- 
    public double MontoUFDepositoA {get;set;}
    public double MontoUFDepositoB {get;set;}
    public double MontoUFDepositoBMayor {get;set;}
    public double MontoUFDepositoAPVA {get;set;}
    public double MontoUFDepositoAPVB {get;set;}
    public double MontoUFDepositoAPVBMayor {get;set;}
    public double MontoUFAporFiscal {get;set;}
    public double MontoUFDevConv {get;set;}
    public double MontoPesoCotizacionAUF {get;set;}
    public double MontoPesoCotizacionBUF {get;set;}
    public double MontoPesoCotizacionBUFMayor {get;set;}
    
    public double MontoPesoDepositoAUF {get;set;}
    public double MontoPesoDepositoBUF {get;set;}
    public double MontoPesoDepositoBUFMayor {get;set;}
    
    
    public double TotalUF {get;set;}
    public boolean CheckboxCotizacionAUF {get;set;}
    public boolean CheckboxCotizacionBUF {get;set;}
    public boolean CheckboxCotizacionBUFMayor {get;set;}
    public boolean CheckboxDepositoAUF {get;set;}
    public boolean CheckboxDepositoBUF {get;set;}
    public boolean CheckboxAporFiscal {get;set;}
    public boolean CheckboxDepositoAPVBMayor {get;set;}
    public boolean CheckboxCotVolBMayor {get;set;}
    public boolean CheckboxDevConv {get;set;}
    public boolean CheckboxCancerFem {get;set;}
    public boolean CheckboxCirugia {get;set;}
    public boolean CheckboxAntCaptTerm {get;set;}
    public boolean CheckboxAyuEnfGrave {get;set;}
    public boolean CheckboxFallecimien {get;set;}
    public boolean CheckboxFallecAccid {get;set;}
    public boolean CheckboxInvalAccide {get;set;}
    public boolean CheckboxRentEducaci {get;set;}
    public boolean CheckboxGtoFunerari {get;set;}
    public double ufVal {get;set;}
    public double numcuentaorigen {get;set;}
    //------------------------------------------------// 
    
}