/*********************************************************************************************************
@Author       zsuanaza@everis.com
@name         OpportunityDataResponse
@CreateDate   26/12/2019
@Description  Class use to get a new executive from analytics
***********************************************************************************************************
History of changes: 
-----------------------------------------------------------------------------------------------------------
Date                               Developer                         Comments   
-----------------------------------------------------------------------------------------------------------
26/12/2019                    zsuanaza@everis.com                Initial Version 
**********************************************************************************************************/
public class OpportunityDataResponse {
    @AuraEnabled public String rutEjecutivo;
}